/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health-проба (БД доступна) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description сервис и БД доступны */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description БД недоступна */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{goszakup_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка контракта по natural goszakup_id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Публичный natural id (НЕ суррогатный bigint) */
                    goszakup_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description контракт найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contract"];
                    };
                };
                /** @description контракт не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description внутренняя ошибка */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{goszakup_id}/flags/{flag_type}/evidence.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Экспорт evidence raised-флага — канонический JSON (Story 5.6, AR-29/SM-5)
         * @description Пересчитываемый третьим лицом/СМИ экспорт evidence ОДНОГО raised-флага контракта. subject_ref — публичный goszakup_contract_id (не суррогатный bigint). Не-raised флаг / отсутствие → 404 (цитировать нечего). Параллельный печатный нейтральный текст — .txt (text/plain, вне JSON-арбитра, как OG-HTML Story 5.5).
         *
         */
        get: {
            parameters: {
                query?: {
                    /** @description язык нейтральной рамки печатного .txt; JSON локаль-агностичен */
                    lang?: "ru" | "kk";
                };
                header?: never;
                path: {
                    goszakup_id: string;
                    flag_type: "single_participant" | "price_per_km";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description канонический экспорт evidence */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvidenceExport"];
                    };
                };
                /** @description нет raised-флага этого типа у контракта (цитировать нечего) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description внутренняя ошибка */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Пороги методики (Story 5.3, FR-23) — единый источник для экрана методики
         * @description Read-only пороги из methodology_params (registry). Экран методики показывает формулу/пороги ВСЕГДА (в т.ч. когда сигнал не выставлен), без литералов на фронте. Иммутабельно в рантайме.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description версия + пороги методики */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Methodology"];
                    };
                };
                /** @description внутренняя ошибка */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/error-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Канал «сообщить об ошибке» (Story 5.4, FR-28) — публичный безаккаунтный досудебный канал
         * @description ПЕРВЫЙ write-эндпоинт. Принимает обращение об ошибке в данных/флаге/геопривязке и кладёт в очередь error_reports (Directus триажит). Защита: honeypot (скрытое поле leave_blank) + лимит тела + rate-limit per-IP. Без аккаунта, без публичного трекинга статуса (PRD §5.11).
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ErrorReportRequest"];
                };
            };
            responses: {
                /** @description обращение принято в очередь */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorReportResponse"];
                    };
                };
                /** @description некорректный вход */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description слишком много обращений (rate-limit) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description внутренняя ошибка */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ⏳ Лоты Астаны с интерим-гео для ранней карты (Story 0.8, трек «Парсер-мост»)
         * @description Временный read-only список scraped-лотов (проекция lots + интерим-гео interim_geo_lots) для ранней карты. ТОЛЬКО лоты — карточки контрактов, флаги, медианы ждут токен ows_v2. Координаты — bare [lon,lat] (nullable; null ⇒ нет точки, НЕ 0,0). Замещается живым импортом при swap scrape→ows.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description список лотов (точки + честные состояния геопривязки) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MapLot"][];
                    };
                };
                /** @description внутренняя ошибка */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StringField: {
            value: string | null;
            /** @enum {string} */
            state: "ok" | "no_data" | "insufficient_sample" | "not_comparable" | "stale" | "geocode_pending" | "geocode_failed" | "source_conflict" | "redacted" | "not_applicable" | "error";
        };
        FlagField: {
            /** @enum {string} */
            state: "raised" | "not_raised" | "insufficient_data" | "not_published";
        };
        Act: {
            present: boolean;
            act_date: components["schemas"]["StringField"];
            signer: components["schemas"]["StringField"];
            source_url: components["schemas"]["StringField"];
        };
        ContractFlag: {
            /** @enum {string} */
            flag_id: "single_participant" | "price_per_km";
            /** @enum {string} */
            state: "raised" | "not_raised" | "insufficient_data" | "not_published";
            methodology_version: components["schemas"]["StringField"];
            detected_at: components["schemas"]["StringField"];
            evidence: {
                [key: string]: unknown;
            } | null;
        };
        MethodologyDrift: {
            present: boolean;
            requested_version: string;
            current_version: string;
        };
        EvidenceExport: {
            /** @enum {string} */
            flag_type: "single_participant" | "price_per_km";
            subject_type: string;
            subject_ref: string;
            methodology_version: string;
            evidence: {
                [key: string]: unknown;
            };
        };
        Contract: {
            goszakup_contract_id: string;
            subject_ru: components["schemas"]["StringField"];
            subject_kk: components["schemas"]["StringField"];
            amount_tng: components["schemas"]["StringField"];
            sign_date: components["schemas"]["StringField"];
            plan_start: components["schemas"]["StringField"];
            plan_end: components["schemas"]["StringField"];
            status: components["schemas"]["StringField"];
            direction: components["schemas"]["StringField"];
            kato_code: components["schemas"]["StringField"];
            customer: components["schemas"]["StringField"];
            supplier: components["schemas"]["StringField"];
            source_url: components["schemas"]["StringField"];
            act: components["schemas"]["Act"];
            flags: components["schemas"]["ContractFlag"][];
            imported_at: components["schemas"]["StringField"];
            updated_at: components["schemas"]["StringField"];
            methodology_version: components["schemas"]["StringField"];
            as_of: components["schemas"]["StringField"];
            methodology_drift: components["schemas"]["MethodologyDrift"];
        };
        /** @description Инвариант координат (OpenAPI 3.0 не выражает условную required-зависимость декларативно, поэтому он задан здесь как контракт): geocode_state = ok ГАРАНТИРУЕТ, что lon и lat не null (точка на карте есть); при ЛЮБОМ другом состоянии (geocode_pending, geocode_failed) lon и lat равны null. Координаты НИКОГДА не равны 0,0. */
        MapLot: {
            goszakup_lot_id: string;
            subject_ru: components["schemas"]["StringField"];
            subject_kk: components["schemas"]["StringField"];
            amount_tng: components["schemas"]["StringField"];
            lon: number | null;
            lat: number | null;
            /** @enum {string} */
            geocode_state: "ok" | "geocode_pending" | "geocode_failed";
        };
        MethodologyThresholds: {
            min_sample: number;
            comparability_window_months: number;
            price_per_km_deviation_factor: number;
            monopoly_concentration_share: number;
            monopoly_min_group_contracts: number;
            single_participant_exclude_methods: string[];
        };
        Methodology: {
            version: string;
            thresholds: components["schemas"]["MethodologyThresholds"];
        };
        ErrorReportRequest: {
            /** @enum {string} */
            kind: "data_error" | "flag_error" | "geo_wrong_point";
            /** @enum {string} */
            subject_type: "contract" | "contractor" | "geo_object";
            subject_ref: string;
            message: string;
            contact?: string;
            source_url?: string;
            leave_blank?: string;
        };
        ErrorReportResponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            status: "received";
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "NOT_FOUND" | "VALIDATION_FAILED" | "INVALID_CURSOR" | "RATE_LIMITED" | "INTERNAL";
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
